# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
### Fetch NuGet Tool ###
- task: NuGetToolInstaller@1

### Install NuGet Tool ###
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

### Build APP (MSBuild) ###
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
#    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    msbuildArgs: '/p:OutputPath=$(build.artifactStagingDirectory)\bin /p:DeployOnBuild=true /p:PublishProfile=veracode.pubxml."'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

### Test App (Unit Tests) ###
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

### Security Scan App Veracode ###
- task: Veracode@2
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode_API'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)\bin'
    createSandBox: false
    createProfile: false
    scanStatusCheckInterval: '60'
    importResults: false
    failBuildOnPolicyFail: false

### Import Veracode Flaws Into Boards ###
- task: Veracode Flaw Importer@2
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode_API'
    veracodeAppProfile: '$(system.teamProject)'
    sandboxName: 
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Task'
    area: '$(system.teamProject)'
    flawImportLimit: '1000'