# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  continueOnError: true

steps:
### Fetch NuGet Tool ###
- task: NuGetToolInstaller@1

### Install NuGet Tool ###
- task: NuGetCommand@2
  displayName: Install NuGet
  inputs:
    restoreSolution: '$(solution)'

### Build APP (MSBuild) ###
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:OutputPath=bin /p:DeployOnBuild=true /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:DebugSymbols=true /p:WDPMergeOption="CreateSeparateAssembly" /p:WebPublishMethod="FileSystem" /p:UseMerge=false'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


### Test App (Unit Tests) ###
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

### Veracode SCA Scan (3rd Party) ###
#- task: PowerShell@2
#  displayName: Veracode SCA
#  inputs:
#    targetType: 'inline'
#    script: |
#         Set-ExecutionPolicy AllSigned -Scope Process -Force
#         $ProgressPreference = "silentlyContinue"
#         iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
#         srcclr scan $(Build.SourcesDirectory)


- task: PowerShell@2
  displayName: Veracode Pipeline Scan
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: |
      Set-ExecutionPolicy AllSigned -Scope Process -Force
      $ProgressPreference = "silentlyContinue"
      (New-Object System.Net.WebClient).DownloadFile('https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip', '/pipeline-scan-LATEST.zip')
      Expand-Archive -force /pipeline-scan-LATEST.zip
      java -jar .\pipeline-scan-LATEST\pipeline-scan.jar -vid $env:API_ID -vkey $env:API_KEY -f "VeraDemoNet/bin/_PublishedWebsites/VeraDemoNet_Package/VeraDemoNet.zip" --fail_on_severity="Very High, High" --json_display true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:\a\1\s\filtered_results.json'
    ArtifactName: 'pipeline scan results'
    publishLocation: 'Container'