# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
### Fetch NuGet Tool ###
- task: NuGetToolInstaller@1

### Install NuGet Tool ###
- task: NuGetCommand@2
  displayName: Install NuGet
  inputs:
    restoreSolution: '$(solution)'

### Build APP (MSBuild) ###
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:OutputPath=bin /p:DeployOnBuild=true /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:DebugSymbols=true /p:WDPMergeOption="CreateSeparateAssembly" /p:WebPublishMethod="FileSystem" /p:UseMerge=false'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


### Test App (Unit Tests) ###
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

### Veracode SCA Scan (3rd Party) ###
- task: PowerShell@2
  displayName: Veracode SCA
  inputs:
    targetType: 'inline'
    script: |
         Set-ExecutionPolicy AllSigned -Scope Process -Force
         $ProgressPreference = "silentlyContinue"
         iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
         srcclr scan $(Build.SourcesDirectory)

### Veracode SAST Scan (1st Party) ###
- task: Veracode@2
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode_API'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: 'VeraDemoNet/bin/_PublishedWebsites/VeraDemoNet_Package/VeraDemoNet.zip'
    createSandBox: false
    createProfile: false
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: false

### Import Veracode Flaws Into Boards ###
- task: Veracode Flaw Importer@2
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode_API'
    veracodeAppProfile: '$(system.teamProject)'
    sandboxName: 
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Task'
    area: '$(system.teamProject)'
    flawImportLimit: '1000'