# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - feature/*

    exclude:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  - group: veracode_variablegroup

stages:
- stage: Build
  jobs:
  - job: VS_Build_DOTNET
    steps:
    - task: NuGetCommand@2
      displayName: Install NuGet
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:OutputPath=bin /p:DeployOnBuild=true /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:DebugSymbols=true /p:WDPMergeOption="CreateSeparateAssembly" /p:WebPublishMethod="FileSystem" /p:UseMerge=false /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)\VeraDemoNet.zip'
        ArtifactName: 'build artifact'
        publishLocation: 'Container'

- stage: Security_Testing
  jobs:
  - job: SAST_Pipeline_Scan
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'build artifact'
        patterns: '**/*.zip'
        path: $(build.artifactstagingdirectory)
    - task: PowerShell@2
      displayName: Pipeline Scan PowerShell
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          Set-ExecutionPolicy AllSigned -Scope Process -Force
          $ProgressPreference = "silentlyContinue"
          (New-Object System.Net.WebClient).DownloadFile('https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip', '/pipeline-scan-LATEST.zip')
          Expand-Archive -force /pipeline-scan-LATEST.zip
          java -jar .\pipeline-scan-LATEST\pipeline-scan.jar --veracode_api_id $VERACODE_API_KEY_ID --veracode_api_key $VERACODE_API_KEY -f $(build.artifactstagingdirectory)\VeraDemoNet.zip --fail_on_severity="Very High, High" --issue_details true

#  - job: Veracode_SCA_Scan
#    steps:
#    - task: PowerShell@2
#      displayName: Veracode SCA
#      inputs:
#        targetType: 'inline'
#        script: |
#          Set-ExecutionPolicy AllSigned -Scope Process -Force
#          $ProgressPreference = "silentlyContinue"
#          iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
#          srcclr scan $(Build.SourcesDirectory)

#    - task: PublishBuildArtifacts@1
#      inputs:
#        PathtoPublish: 'D:\a\1\s\filtered_results.json'
#        ArtifactName: 'pipeline scan results'
#        publishLocation: 'Container'