# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - releases/*
    exclude:
    - master
pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: veracode_variablegroup

steps:
      - task: NuGetCommand@2
        displayName: Install NuGet
        inputs:
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)/" /p:DebugSymbols=true'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: Veracode@3
        inputs:
          ConnectionDetailsSelection: 'Endpoint'
          AnalysisService: 'Veracode_API'
          veracodeAppProfile: '$(system.teamProject)'
          version: '$(build.buildNumber)'
          filepath: '$(build.artifactstagingdirectory)\VeraDemoNet.zip'
          createProfile: false
          failTheBuildIfVeracodeScanDidNotInitiate: false
          createSandBox: false
          scanStatusCheckInterval: '60'
          importResults: true
          failBuildOnPolicyFail: false

      - task: Veracode Flaw Importer@3
        inputs:
          ConnectionDetailsSelection: 'Endpoint'
          AnalysisService: 'Veracode_API'
          veracodeAppProfile: '$(system.teamProject)'
          sandboxName: 
          importType: 'All Flaws'
          workItemType: 'Bug'
          area: '$(system.teamProject)'
          flawImportLimit: '1000'

#      - task: PublishBuildArtifacts@1
#        inputs:
#          PathtoPublish: 'D:\a\1\s\filtered_results.json'
#          ArtifactName: 'pipeline scan results'
#          publishLocation: 'Container'

### Veracode SCA Scan (3rd Party) ###
#- task: PowerShell@2
#  displayName: Veracode SCA
#  inputs:
#    targetType: 'inline'
#    script: |
#         Set-ExecutionPolicy AllSigned -Scope Process -Force
#         $ProgressPreference = "silentlyContinue"
#         iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
#         srcclr scan $(Build.SourcesDirectory)










        
          

